### ISSUE TITLE
Duda con el temario

### ISSUE THREAD

**Issue by arigroisman** [infiniemlabs-acustica/python_audio#3]
@maxiyommi que pongo en la unidad 3

**Comment by maxiyommi** [comment]
En el README.md, esta el temario. 

Unidad 3 – Procesamiento, análisis y visualización de datos/señales

    Librerías para manipulación de datos numéricos.
    Arrays de datos.
    Tipos de datos numéricos.
    Operaciones entre arrays.
    Implementación de gráficos de datos.
    Análisis de estructuras de datos.
    Librería para procesamiento de señales.
    Aplicación de FFT.
    Convolución.
